# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25671e86ac049b47d795f66e5b1746253a50e63a9cf001b43d6cea1a6406c6f344cab8ebbb9f991509f69f4cdc8d6b2676e06aac3dfd12485763965e75e242a0

test:
  secret_key_base: f5d4bc9b63b3a3fad5fd2d9100bfe98a65b900da5ae85b3b4c3385d163f73b58edab39dcde5f8b0633395e337ddb4cc4a503761726a3899decb7242532848261

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
